/**
 * Icon shim — maps the icon names the app historically imported from `lucide-react`
 * onto Phosphor Icons (@phosphor-icons/react). Import icons from "@/lib/icons"
 * everywhere instead of "lucide-react"; the whole app renders Phosphor's cleaner,
 * modern SVG set with a single point of control.
 *
 * Default weight/size for all icons is set via IconContext in main.tsx.
 */
export {
  Pulse as Activity,
  WarningCircle as AlertCircle,
  Warning as AlertTriangle,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowLineDown as ArrowDownToLine,
  ArrowLeft,
  ArrowLineUp as ArrowUpFromLine,
  ArrowUpRight,
  Money as Banknote,
  ChartBar as BarChart3,
  ChartLineUp,
  Bell,
  Buildings as Building2,
  CalendarBlank as Calendar,
  CalendarCheck as CalendarClock,
  Check,
  CheckCircle,
  CheckCircle as CheckCircle2,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  CaretDoubleLeft as ChevronsLeft,
  CaretDoubleRight as ChevronsRight,
  CaretUpDown as ChevronsUpDown,
  Circle,
  Clock,
  Copy,
  CreditCard,
  Crosshair,
  CurrencyDollar as DollarSign,
  DownloadSimple as Download,
  PencilSimple as Edit,
  ArrowSquareOut as ExternalLink,
  Eye,
  EyeSlash as EyeOff,
  FileMagnifyingGlass as FileSearch,
  FileXls as FileSpreadsheet,
  FileText,
  FileArrowUp as FileUp,
  Funnel as Filter,
  Globe,
  HandCoins,
  Hash,
  House as Home,
  IdentificationCard as IdCard,
  Info,
  Key as KeyRound,
  SquaresFour as LayoutDashboard,
  CircleNotch as Loader2,
  Lock,
  SignOut as LogOut,
  Envelope as Mail,
  MapPin,
  List as Menu,
  NavigationArrow as Navigation,
  Package,
  Pencil,
  Percent,
  Phone,
  Plus,
  Printer,
  QrCode,
  Receipt,
  Recycle,
  ArrowsClockwise as RefreshCw,
  ArrowsClockwise,
  ArrowClockwise as RotateCw,
  Ruler,
  FloppyDisk as Save,
  Scan as ScanLine,
  MagnifyingGlass as Search,
  Gear as Settings,
  Shield,
  SlidersHorizontal,
  DeviceMobile as Smartphone,
  Trash as Trash2,
  TrendDown as TrendingDown,
  TrendUp as TrendingUp,
  Trophy,
  Truck,
  LockOpen as Unlock,
  UploadSimple as Upload,
  User,
  UserGear as UserCog,
  UserPlus,
  Users,
  Wallet,
  X,
  XCircle,
  WhatsappLogo,
  ChatText,
} from "@phosphor-icons/react";

export type { Icon as LucideIcon } from "@phosphor-icons/react";
